services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: sitore_admin
      POSTGRES_PASSWORD: sitore123
      POSTGRES_DB: sitore
    ports:
      - "5434:5432"
    volumes:
      - sitore_pg_data:/var/lib/postgresql/data

volumes:
  sitore_pg_data:
